#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MoneyTracker_01.Resource", IsApplication=true)]

namespace MoneyTracker_01
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int bankList = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int btnBanks = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int btnExpencies = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int btnGroups = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int btnSavebank = 2130968579;
			
			// aapt resource value: 0x7f040008
			public const int btnSavegroup = 2130968584;
			
			// aapt resource value: 0x7f040001
			public const int edtBankname = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int edtDate = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int edtGroupname = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int edtMoney = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int groupList = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int listViewBanks = 2130968580;
			
			// aapt resource value: 0x7f040009
			public const int listViewGroups = 2130968585;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Banks = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BList = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int GList = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Groups = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Main = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
